export const ADD_PACKAGE_ORDER = "ADD_PACKAGE_ORDER";

export const ADD_PACKAGE_ORDER_SUCCESS = "ADD_PACKAGE_ORDER_SUCCESS";
export const ADD_PACKAGE_ORDER_FAIL = "ADD_PACKAGE_ORDER_FAIL";

export const GET_USER_ORDER = "GET_USER_ORDER";
export const GET_USER_ORDER_SUCCESS = "GET_USER_ORDER_SUCCESS";
export const GET_USER_ORDER_FAIL = "GET_USER_ORDER_FAIL";


