export const POST_CATEGORY = "POST_CATEGORY"
export const POST_CATEGORY_SUCCESSFUL = "POST_CATEGORY_SUCCESSFUL"
export const POST_CATEGORY_FAILED = "POST_CATEGORY_FAILED"

export const GET_CATEGORY = "GET_CATEGORY"
export const GET_CATEGORY_SUCCESSFUL = "GET_CATEGORY_SUCCESSFUL"
export const GET_CATEGORY_FAILED = "GET_CATEGORY_FAILED"

export const POST_SHOP = "POST_SHOP"
export const POST_SHOP_SUCCESSFUL = "POST_SHOP_SUCCESSFUL"
export const POST_SHOP_FAILED = "POST_SHOP_FAILED"


export const GET_SHOP = "GET_SHOP"
export const GET_SHOP_SUCCESSFUL = "GET_SHOP_SUCCESSFUL"
export const GET_SHOP_FAILED = "GET_SHOP_FAILED"

export const POST_PRODUCT = "POST_PRODUCT"
export const POST_PRODUCT_SUCCESSFUL = "POST_PRODUCT_SUCCESSFUL"
export const POST_PRODUCT_FAILED = "POST_PRODUCT_FAILED"


export const GET_PRODUCT = "GET_PRODUCT"
export const GET_PRODUCT_SUCCESSFUL = "GET_PRODUCT_SUCCESSFUL"
export const GET_PRODUCT_FAILED = "GET_PRODUCT_FAILED"

export const GET_EMPLOYEE = "GET_EMPLOYEE"
export const GET_EMPLOYEE_SUCCESSFUL = "GET_EMPLOYEE_SUCCESSFUL"
export const GET_EMPLOYEE_FAILED = "GET_EMPLOYEE_FAILED"

export const POST_EMPLOYEE = "POST_EMPLOYEE"
export const POST_EMPLOYEE_SUCCESSFUL = "POST_EMPLOYEE_SUCCESSFUL"
export const POST_EMPLOYEE_FAILED = "POST_EMPLOYEE_FAILED"

export const GET_SHOP_PRODUCT = "GET_SHOP_PRODUCT"
export const GET_SHOP_PRODUCT_SUCCESSFUL = "GET_SHOP_PRODUCT_SUCCESSFUL"
export const GET_SHOP_PRODUCT_FAILED = "GET_SHOP_PRODUCT_FAILED"